//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Proxy1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy1.IChekkers", CallbackContract=typeof(Client.Proxy1.IChekkersCallback))]
    public interface IChekkers {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChekkers/Join")]
        void Join(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChekkers/Join")]
        System.Threading.Tasks.Task JoinAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChekkers/MoveMade")]
        void MoveMade(int oldCoord_X, int oldCoord_Y, int newCoord_X, int newCoord_Y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChekkers/MoveMade")]
        System.Threading.Tasks.Task MoveMadeAsync(int oldCoord_X, int oldCoord_Y, int newCoord_X, int newCoord_Y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChekkersCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChekkers/move")]
        void move(int oldCoord_X, int oldCoord_Y, int newCoord_X, int newCoord_Y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChekkersChannel : Client.Proxy1.IChekkers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChekkersClient : System.ServiceModel.DuplexClientBase<Client.Proxy1.IChekkers>, Client.Proxy1.IChekkers {
        
        public ChekkersClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChekkersClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChekkersClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChekkersClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChekkersClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join(string name) {
            base.Channel.Join(name);
        }
        
        public System.Threading.Tasks.Task JoinAsync(string name) {
            return base.Channel.JoinAsync(name);
        }
        
        public void MoveMade(int oldCoord_X, int oldCoord_Y, int newCoord_X, int newCoord_Y) {
            base.Channel.MoveMade(oldCoord_X, oldCoord_Y, newCoord_X, newCoord_Y);
        }
        
        public System.Threading.Tasks.Task MoveMadeAsync(int oldCoord_X, int oldCoord_Y, int newCoord_X, int newCoord_Y) {
            return base.Channel.MoveMadeAsync(oldCoord_X, oldCoord_Y, newCoord_X, newCoord_Y);
        }
    }
}
